// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNIItZhmPG7Mkkat1_241EaMfVCpOb0lU',
    appId: '1:254551726880:web:655e6c60e64d2c61651545',
    messagingSenderId: '254551726880',
    projectId: 'meal-planner-e885c',
    authDomain: 'meal-planner-e885c.firebaseapp.com',
    storageBucket: 'meal-planner-e885c.firebasestorage.app',
    measurementId: 'G-DCPTB3M9Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq0SVBQBjY-gbxLXUiYQq-J8Ub-qDuF6U',
    appId: '1:254551726880:android:358035ce1e65643c651545',
    messagingSenderId: '254551726880',
    projectId: 'meal-planner-e885c',
    storageBucket: 'meal-planner-e885c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQelpjt7EsKARueqo2_epM_Zef6h_YsEM',
    appId: '1:254551726880:ios:d6fbf3c731ed1408651545',
    messagingSenderId: '254551726880',
    projectId: 'meal-planner-e885c',
    storageBucket: 'meal-planner-e885c.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQelpjt7EsKARueqo2_epM_Zef6h_YsEM',
    appId: '1:254551726880:ios:d6fbf3c731ed1408651545',
    messagingSenderId: '254551726880',
    projectId: 'meal-planner-e885c',
    storageBucket: 'meal-planner-e885c.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNIItZhmPG7Mkkat1_241EaMfVCpOb0lU',
    appId: '1:254551726880:web:c2ec0e64d9a3dfd1651545',
    messagingSenderId: '254551726880',
    projectId: 'meal-planner-e885c',
    authDomain: 'meal-planner-e885c.firebaseapp.com',
    storageBucket: 'meal-planner-e885c.firebasestorage.app',
    measurementId: 'G-13EP6GL83E',
  );
}
